# Generated by Django 3.0 on 2019-12-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=30)),
                ('local', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('status', models.CharField(default='I', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('redesocial', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=14)),
                ('participacoes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torneio', models.CharField(max_length=30)),
                ('qtd_etapas', models.IntegerField()),
                ('qtd_rebuy', models.IntegerField()),
                ('qtd_players', models.IntegerField()),
                ('vlr_buyinn', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vlr_rebuy', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vlr_jackpot', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_inn', models.IntegerField()),
                ('qtd_rebuy', models.IntegerField()),
                ('posicao', models.IntegerField()),
                ('pontuacao', models.IntegerField()),
                ('premio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pkapp.Etapas')),
                ('id_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pkapp.Players')),
                ('id_torneio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pkapp.Torneios')),
            ],
        ),
        migrations.AddField(
            model_name='etapas',
            name='id_torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pkapp.Torneios'),
        ),
    ]
